### ISSUE TITLE
Sociel Profile ID return integer

### ISSUE THREAD

**Issue by hongmingChm** [intercom/intercom-go#104]
## Version info
  - intercom-go version: v2
  - Go version: go version go1.10.1 linux/amd64

## Expected behavior
Social Profile ID should return string instead of integer as defined in
`https://github.com/intercom/intercom-go/blob/v2/user.go#L70`

## Actual behavior
During one of the calls to API to retrieve certain user
the Twitter Profile ID returned is integer instead.
This caused an error `cannot unmarshal number into Go struct field SocialProfile.id of type string` in `https://github.com/intercom/intercom-go/blob/v2/user_api.go#L93`

## Steps to reproduce
This error occurs on certain user from API response.

## Logs
N/A

## Action taken
Contacted Support in Intercom and they seems to notified engineer.
However, it's been months since I last reported and no action had been taken.

**Comment by dolmen** [comment]
This is a server-side issue. Not an issue about this Go package.

Relevant API documentation which mention that a social profile `id` is a string:
https://developers.intercom.com/intercom-api-reference/reference#section-social-profile-object

**Comment by choran** [comment]
Yes, this is not an issue with the SDK as such. We have an internal issue tracking this and the solution will be to ensure that a string is always returned from the API which will then resolve any issue in the SDKs.
This is on our list of issues here so we will get to it but I cannot provide a specific timeframe.
For now I will close this issue since it is not an SDK issue but will provide an update when we fix it on our side
